/**
 * Nordic Recipient Admin App
 * TODO/Following David's template
 *
 * OpenAPI spec version: 1.0.0
 * Contact: david.hultsberg@postnord.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NordicRecipientAdminApp);
  }
}(this, function(expect, NordicRecipientAdminApp) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NordicRecipientAdminApp.DeliveryAddress();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DeliveryAddress', function() {
    it('should create an instance of DeliveryAddress', function() {
      // uncomment below and update the code to test DeliveryAddress
      //var instane = new NordicRecipientAdminApp.DeliveryAddress();
      //expect(instance).to.be.a(NordicRecipientAdminApp.DeliveryAddress);
    });

    it('should have the property objectId (base name: "object_id")', function() {
      // uncomment below and update the code to test the property objectId
      //var instane = new NordicRecipientAdminApp.DeliveryAddress();
      //expect(instance).to.be();
    });

    it('should have the property mailDeliveryRouteId (base name: "mail_delivery_route_id")', function() {
      // uncomment below and update the code to test the property mailDeliveryRouteId
      //var instane = new NordicRecipientAdminApp.DeliveryAddress();
      //expect(instance).to.be();
    });

    it('should have the property stopPointId (base name: "stop_point_id")', function() {
      // uncomment below and update the code to test the property stopPointId
      //var instane = new NordicRecipientAdminApp.DeliveryAddress();
      //expect(instance).to.be();
    });

    it('should have the property postalCode (base name: "postal_code")', function() {
      // uncomment below and update the code to test the property postalCode
      //var instane = new NordicRecipientAdminApp.DeliveryAddress();
      //expect(instance).to.be();
    });

    it('should have the property streetAddress (base name: "street_address")', function() {
      // uncomment below and update the code to test the property streetAddress
      //var instane = new NordicRecipientAdminApp.DeliveryAddress();
      //expect(instance).to.be();
    });

    it('should have the property addressPosition (base name: "address_position")', function() {
      // uncomment below and update the code to test the property addressPosition
      //var instane = new NordicRecipientAdminApp.DeliveryAddress();
      //expect(instance).to.be();
    });

    it('should have the property sequenceNumber (base name: "sequence_number")', function() {
      // uncomment below and update the code to test the property sequenceNumber
      //var instane = new NordicRecipientAdminApp.DeliveryAddress();
      //expect(instance).to.be();
    });

    it('should have the property metadata (base name: "metadata")', function() {
      // uncomment below and update the code to test the property metadata
      //var instane = new NordicRecipientAdminApp.DeliveryAddress();
      //expect(instance).to.be();
    });

  });

}));
