/**
 * Nordic Recipient Admin App
 * TODO/Following David's template
 *
 * OpenAPI spec version: 1.0.0
 * Contact: david.hultsberg@postnord.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NordicRecipientAdminApp);
  }
}(this, function(expect, NordicRecipientAdminApp) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NordicRecipientAdminApp.RecipientGroup();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RecipientGroup', function() {
    it('should create an instance of RecipientGroup', function() {
      // uncomment below and update the code to test RecipientGroup
      //var instane = new NordicRecipientAdminApp.RecipientGroup();
      //expect(instance).to.be.a(NordicRecipientAdminApp.RecipientGroup);
    });

    it('should have the property deliveryPointId (base name: "delivery_point_id")', function() {
      // uncomment below and update the code to test the property deliveryPointId
      //var instane = new NordicRecipientAdminApp.RecipientGroup();
      //expect(instance).to.be();
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instane = new NordicRecipientAdminApp.RecipientGroup();
      //expect(instance).to.be();
    });

    it('should have the property recipientGroupType (base name: "recipient_group_type")', function() {
      // uncomment below and update the code to test the property recipientGroupType
      //var instane = new NordicRecipientAdminApp.RecipientGroup();
      //expect(instance).to.be();
    });

    it('should have the property metadata (base name: "metadata")', function() {
      // uncomment below and update the code to test the property metadata
      //var instane = new NordicRecipientAdminApp.RecipientGroup();
      //expect(instance).to.be();
    });

  });

}));
