/**
 * Nordic Recipient Admin App
 * TODO/Following David's template
 *
 * OpenAPI spec version: 1.0.0
 * Contact: david.hultsberg@postnord.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import DeliveryAddress from '../model/DeliveryAddress';

/**
* DeliveryAddress service.
* @module api/DeliveryAddressApi
* @version 1.0.0
*/
export default class DeliveryAddressApi {

    /**
    * Constructs a new DeliveryAddressApi. 
    * @alias module:api/DeliveryAddressApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the findDeliveryAddresses operation.
     * @callback module:api/DeliveryAddressApi~findDeliveryAddressesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/DeliveryAddress>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Finds delivery addresses by route name
     * @param {String} routeName api allows starts-with 2 first characters
     * @param {module:api/DeliveryAddressApi~findDeliveryAddressesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/DeliveryAddress>}
     */
    findDeliveryAddresses(routeName, callback) {
      let postBody = null;

      // verify the required parameter 'routeName' is set
      if (routeName === undefined || routeName === null) {
        throw new Error("Missing the required parameter 'routeName' when calling findDeliveryAddresses");
      }


      let pathParams = {
      };
      let queryParams = {
        'route name': routeName
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth', 'OAuth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [DeliveryAddress];

      return this.apiClient.callApi(
        '/deliveryAddresses', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }


}
