/**
 * Nordic Recipient Admin App
 * TODO/Following David's template
 *
 * OpenAPI spec version: 1.0.0
 * Contact: david.hultsberg@postnord.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import MailDeliveryRoute from '../model/MailDeliveryRoute';

/**
* Route service.
* @module api/RouteApi
* @version 1.0.0
*/
export default class RouteApi {

    /**
    * Constructs a new RouteApi. 
    * @alias module:api/RouteApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the findRoutes operation.
     * @callback module:api/RouteApi~findRoutesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/MailDeliveryRoute>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Finds Routes by name
     * Muliple tags can be provided with comma separated strings. Use\\ \\ tag1, tag2, tag3 for testing.
     * @param {String} name api allows starts-with 2 first characters
     * @param {module:api/RouteApi~findRoutesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/MailDeliveryRoute>}
     */
    findRoutes(name, callback) {
      let postBody = null;

      // verify the required parameter 'name' is set
      if (name === undefined || name === null) {
        throw new Error("Missing the required parameter 'name' when calling findRoutes");
      }


      let pathParams = {
      };
      let queryParams = {
        'name': name
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth', 'OAuth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [MailDeliveryRoute];

      return this.apiClient.callApi(
        '/routes', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }


}
