---
swagger: "2.0"
info:
  version: "0.0.1"
  title: "Hello World App"
host: "localhost:10010"
basePath: "/"
schemes:
- "http"
- "https"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /recipients:
    get:
      summary: "Get all recipients"
      operationId: "findRecipients"
      parameters:
      - name: "name"
        in: "query"
        description: "Find recipients by name"
        required: true
        type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Recipient"
      x-swagger-router-controller: "Default"
  /hello:
    get:
      description: "Returns 'Hello' to the caller"
      operationId: "hello"
      parameters:
      - name: "name"
        in: "query"
        description: "The name of the person to whom to say hello"
        required: false
        type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/HelloWorldResponse"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
      x-swagger-router-controller: "Default"
    x-swagger-router-controller: "hello_world"
  /swagger:
    x-swagger-pipe: "swagger_raw"
definitions:
  DeliveryPoint:
    type: "object"
    required:
    - "object_id"
    properties:
      object_id:
        type: "string"
        format: "uuid"
      delivery_address_id:
        type: "string"
        format: "uuid"
      apartment_number:
        type: "string"
      decline_odr:
        type: "boolean"
      decline_gt:
        type: "boolean"
      floor:
        type: "string"
    description: "The delivery end point for mail"
  Recipient:
    type: "object"
    required:
    - "object_id"
    properties:
      object_id:
        type: "string"
        format: "uuid"
      delivery_point_id:
        type: "string"
        format: "uuid"
      firstname:
        type: "string"
      lastname:
        type: "string"
      private_recipient:
        type: "boolean"
      expiration_date:
        type: "string"
        format: "date-time"
      starting_date:
        type: "string"
        format: "date-time"
    description: "A recipient (person) that resides at a delivery point. TODO consider\
      \ naming it recipient instead"
    example:
      firstname: "firstname"
      delivery_point_id: "046b6c7f-0b8a-43b9-b35d-6489e6daee91"
      starting_date: "2000-01-23T04:56:07.000+00:00"
      expiration_date: "2000-01-23T04:56:07.000+00:00"
      object_id: "046b6c7f-0b8a-43b9-b35d-6489e6daee91"
      private_recipient: true
      lastname: "lastname"
  HelloWorldResponse:
    required:
    - "message"
    properties:
      message:
        type: "string"
    example:
      message: "message"
  ErrorResponse:
    required:
    - "message"
    properties:
      message:
        type: "string"
