/**
 * Nordic Recipient Admin App
 * TODO/Following David's template
 *
 * OpenAPI spec version: 1.0.0
 * Contact: david.hultsberg@postnord.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Metadata from './Metadata';





/**
* The DeliveryAddress model module.
* @module model/DeliveryAddress
* @version 1.0.0
*/
export default class DeliveryAddress {
    /**
    * Constructs a new <code>DeliveryAddress</code>.
    * The delivery address for mail
    * @alias module:model/DeliveryAddress
    * @class
    * @param metadata {module:model/Metadata} 
    */

    constructor(metadata) {
        

        
        

        this['metadata'] = metadata;

        
    }

    /**
    * Constructs a <code>DeliveryAddress</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/DeliveryAddress} obj Optional instance to populate.
    * @return {module:model/DeliveryAddress} The populated <code>DeliveryAddress</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeliveryAddress();

            
            
            

            if (data.hasOwnProperty('object_id')) {
                obj['object_id'] = ApiClient.convertToType(data['object_id'], 'String');
            }
            if (data.hasOwnProperty('mail_delivery_route_id')) {
                obj['mail_delivery_route_id'] = ApiClient.convertToType(data['mail_delivery_route_id'], 'String');
            }
            if (data.hasOwnProperty('stop_point_id')) {
                obj['stop_point_id'] = ApiClient.convertToType(data['stop_point_id'], 'String');
            }
            if (data.hasOwnProperty('postal_code')) {
                obj['postal_code'] = ApiClient.convertToType(data['postal_code'], 'String');
            }
            if (data.hasOwnProperty('street_address')) {
                obj['street_address'] = ApiClient.convertToType(data['street_address'], 'String');
            }
            if (data.hasOwnProperty('address_position')) {
                obj['address_position'] = ApiClient.convertToType(data['address_position'], 'Number');
            }
            if (data.hasOwnProperty('sequence_number')) {
                obj['sequence_number'] = ApiClient.convertToType(data['sequence_number'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = Metadata.constructFromObject(data['metadata']);
            }
        }
        return obj;
    }

    /**
    * @member {String} object_id
    */
    object_id = undefined;
    /**
    * @member {String} mail_delivery_route_id
    */
    mail_delivery_route_id = undefined;
    /**
    * @member {String} stop_point_id
    */
    stop_point_id = undefined;
    /**
    * @member {String} postal_code
    */
    postal_code = undefined;
    /**
    * @member {String} street_address
    */
    street_address = undefined;
    /**
    * @member {Number} address_position
    */
    address_position = undefined;
    /**
    * @member {String} sequence_number
    */
    sequence_number = undefined;
    /**
    * @member {module:model/Metadata} metadata
    */
    metadata = undefined;








}


