/**
 * Nordic Recipient Admin App
 * TODO/Following David's template
 *
 * OpenAPI spec version: 1.0.0
 * Contact: david.hultsberg@postnord.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Metadata from './Metadata';





/**
* The DeliveryPoint model module.
* @module model/DeliveryPoint
* @version 1.0.0
*/
export default class DeliveryPoint {
    /**
    * Constructs a new <code>DeliveryPoint</code>.
    * The delivery end point for mail
    * @alias module:model/DeliveryPoint
    * @class
    * @param metadata {module:model/Metadata} 
    */

    constructor(metadata) {
        

        
        

        this['metadata'] = metadata;

        
    }

    /**
    * Constructs a <code>DeliveryPoint</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/DeliveryPoint} obj Optional instance to populate.
    * @return {module:model/DeliveryPoint} The populated <code>DeliveryPoint</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeliveryPoint();

            
            
            

            if (data.hasOwnProperty('object_id')) {
                obj['object_id'] = ApiClient.convertToType(data['object_id'], 'String');
            }
            if (data.hasOwnProperty('delivery_address_id')) {
                obj['delivery_address_id'] = ApiClient.convertToType(data['delivery_address_id'], 'String');
            }
            if (data.hasOwnProperty('apartment_number')) {
                obj['apartment_number'] = ApiClient.convertToType(data['apartment_number'], 'String');
            }
            if (data.hasOwnProperty('sequence_number')) {
                obj['sequence_number'] = ApiClient.convertToType(data['sequence_number'], 'String');
            }
            if (data.hasOwnProperty('decline_odr')) {
                obj['decline_odr'] = ApiClient.convertToType(data['decline_odr'], 'Boolean');
            }
            if (data.hasOwnProperty('decline_gt')) {
                obj['decline_gt'] = ApiClient.convertToType(data['decline_gt'], 'Boolean');
            }
            if (data.hasOwnProperty('floor')) {
                obj['floor'] = ApiClient.convertToType(data['floor'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = Metadata.constructFromObject(data['metadata']);
            }
        }
        return obj;
    }

    /**
    * @member {String} object_id
    */
    object_id = undefined;
    /**
    * @member {String} delivery_address_id
    */
    delivery_address_id = undefined;
    /**
    * @member {String} apartment_number
    */
    apartment_number = undefined;
    /**
    * @member {String} sequence_number
    */
    sequence_number = undefined;
    /**
    * @member {Boolean} decline_odr
    */
    decline_odr = undefined;
    /**
    * @member {Boolean} decline_gt
    */
    decline_gt = undefined;
    /**
    * @member {String} floor
    */
    floor = undefined;
    /**
    * @member {module:model/Metadata} metadata
    */
    metadata = undefined;








}


