/**
 * Nordic Recipient Admin App
 * TODO/Following David's template
 *
 * OpenAPI spec version: 1.0.0
 * Contact: david.hultsberg@postnord.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Metadata from './Metadata';





/**
* The MailDeliveryRoute model module.
* @module model/MailDeliveryRoute
* @version 1.0.0
*/
export default class MailDeliveryRoute {
    /**
    * Constructs a new <code>MailDeliveryRoute</code>.
    * TODO
    * @alias module:model/MailDeliveryRoute
    * @class
    * @param metadata {module:model/Metadata} 
    */

    constructor(metadata) {
        

        
        

        this['metadata'] = metadata;

        
    }

    /**
    * Constructs a <code>MailDeliveryRoute</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MailDeliveryRoute} obj Optional instance to populate.
    * @return {module:model/MailDeliveryRoute} The populated <code>MailDeliveryRoute</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MailDeliveryRoute();

            
            
            

            if (data.hasOwnProperty('object_id')) {
                obj['object_id'] = ApiClient.convertToType(data['object_id'], 'String');
            }
            if (data.hasOwnProperty('delivery_office_id')) {
                obj['delivery_office_id'] = ApiClient.convertToType(data['delivery_office_id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('sequence_number')) {
                obj['sequence_number'] = ApiClient.convertToType(data['sequence_number'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = Metadata.constructFromObject(data['metadata']);
            }
        }
        return obj;
    }

    /**
    * @member {String} object_id
    */
    object_id = undefined;
    /**
    * @member {String} delivery_office_id
    */
    delivery_office_id = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} sequence_number
    */
    sequence_number = undefined;
    /**
    * @member {module:model/Metadata} metadata
    */
    metadata = undefined;








}


