/**
 * Nordic Recipient Admin App
 * TODO/Following David's template
 *
 * OpenAPI spec version: 1.0.0
 * Contact: david.hultsberg@postnord.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Metadata from './Metadata';





/**
* The Recipient model module.
* @module model/Recipient
* @version 1.0.0
*/
export default class Recipient {
    /**
    * Constructs a new <code>Recipient</code>.
    * A recipient (person) that resides at a delivery point. TODO consider naming it recipient instead
    * @alias module:model/Recipient
    * @class
    * @param metadata {module:model/Metadata} 
    */

    constructor(metadata) {
        

        
        

        this['metadata'] = metadata;

        
    }

    /**
    * Constructs a <code>Recipient</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Recipient} obj Optional instance to populate.
    * @return {module:model/Recipient} The populated <code>Recipient</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Recipient();

            
            
            

            if (data.hasOwnProperty('delivery_point_id')) {
                obj['delivery_point_id'] = ApiClient.convertToType(data['delivery_point_id'], 'String');
            }
            if (data.hasOwnProperty('firstname')) {
                obj['firstname'] = ApiClient.convertToType(data['firstname'], 'String');
            }
            if (data.hasOwnProperty('lastname')) {
                obj['lastname'] = ApiClient.convertToType(data['lastname'], 'String');
            }
            if (data.hasOwnProperty('sequence_number')) {
                obj['sequence_number'] = ApiClient.convertToType(data['sequence_number'], 'String');
            }
            if (data.hasOwnProperty('private_recipient')) {
                obj['private_recipient'] = ApiClient.convertToType(data['private_recipient'], 'Boolean');
            }
            if (data.hasOwnProperty('expiration_date')) {
                obj['expiration_date'] = ApiClient.convertToType(data['expiration_date'], 'Date');
            }
            if (data.hasOwnProperty('starting_date')) {
                obj['starting_date'] = ApiClient.convertToType(data['starting_date'], 'Date');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = Metadata.constructFromObject(data['metadata']);
            }
        }
        return obj;
    }

    /**
    * @member {String} delivery_point_id
    */
    delivery_point_id = undefined;
    /**
    * @member {String} firstname
    */
    firstname = undefined;
    /**
    * @member {String} lastname
    */
    lastname = undefined;
    /**
    * @member {String} sequence_number
    */
    sequence_number = undefined;
    /**
    * @member {Boolean} private_recipient
    */
    private_recipient = undefined;
    /**
    * @member {Date} expiration_date
    */
    expiration_date = undefined;
    /**
    * @member {Date} starting_date
    */
    starting_date = undefined;
    /**
    * @member {module:model/Metadata} metadata
    */
    metadata = undefined;








}


