/**
 * Nordic Recipient Admin App
 * TODO/Following David's template
 *
 * OpenAPI spec version: 1.0.0
 * Contact: david.hultsberg@postnord.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Metadata from './Metadata';
import StopPointStopPointType from './StopPointStopPointType';





/**
* The StopPoint model module.
* @module model/StopPoint
* @version 1.0.0
*/
export default class StopPoint {
    /**
    * Constructs a new <code>StopPoint</code>.
    * TODO
    * @alias module:model/StopPoint
    * @class
    * @param metadata {module:model/Metadata} 
    */

    constructor(metadata) {
        

        
        

        this['metadata'] = metadata;

        
    }

    /**
    * Constructs a <code>StopPoint</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/StopPoint} obj Optional instance to populate.
    * @return {module:model/StopPoint} The populated <code>StopPoint</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StopPoint();

            
            
            

            if (data.hasOwnProperty('object_id')) {
                obj['object_id'] = ApiClient.convertToType(data['object_id'], 'String');
            }
            if (data.hasOwnProperty('stop_point_type')) {
                obj['stop_point_type'] = StopPointStopPointType.constructFromObject(data['stop_point_type']);
            }
            if (data.hasOwnProperty('delivery_address_id')) {
                obj['delivery_address_id'] = ApiClient.convertToType(data['delivery_address_id'], 'String');
            }
            if (data.hasOwnProperty('information')) {
                obj['information'] = ApiClient.convertToType(data['information'], 'String');
            }
            if (data.hasOwnProperty('door_code')) {
                obj['door_code'] = ApiClient.convertToType(data['door_code'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = Metadata.constructFromObject(data['metadata']);
            }
        }
        return obj;
    }

    /**
    * @member {String} object_id
    */
    object_id = undefined;
    /**
    * @member {module:model/StopPointStopPointType} stop_point_type
    */
    stop_point_type = undefined;
    /**
    * @member {String} delivery_address_id
    */
    delivery_address_id = undefined;
    /**
    * @member {String} information
    */
    information = undefined;
    /**
    * @member {String} door_code
    */
    door_code = undefined;
    /**
    * @member {module:model/Metadata} metadata
    */
    metadata = undefined;








}


