/**
 * Nordic Recipient Admin App
 * TODO/Following David's template
 *
 * OpenAPI spec version: 1.0.0
 * Contact: david.hultsberg@postnord.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The StopPointStopPointType model module.
* @module model/StopPointStopPointType
* @version 1.0.0
*/
export default class StopPointStopPointType {
    /**
    * Constructs a new <code>StopPointStopPointType</code>.
    * @alias module:model/StopPointStopPointType
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>StopPointStopPointType</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/StopPointStopPointType} obj Optional instance to populate.
    * @return {module:model/StopPointStopPointType} The populated <code>StopPointStopPointType</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StopPointStopPointType();

            
            
            

            if (data.hasOwnProperty('object_id')) {
                obj['object_id'] = ApiClient.convertToType(data['object_id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} object_id
    */
    object_id = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} label
    */
    label = undefined;








}


