/**
 * Nordic Recipient Admin App
 * TODO/Following David's template
 *
 * OpenAPI spec version: 1.0.0
 * Contact: david.hultsberg@postnord.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import DeliveryAddress from './model/DeliveryAddress';
import DeliveryOffice from './model/DeliveryOffice';
import DeliveryPoint from './model/DeliveryPoint';
import MailDeliveryRoute from './model/MailDeliveryRoute';
import Metadata from './model/Metadata';
import Recipient from './model/Recipient';
import RecipientGroup from './model/RecipientGroup';
import StopPoint from './model/StopPoint';
import StopPointStopPointType from './model/StopPointStopPointType';
import DefaultApi from './api/DefaultApi';
import DeliveryAddressApi from './api/DeliveryAddressApi';
import DeliveryPointApi from './api/DeliveryPointApi';
import RouteApi from './api/RouteApi';


/**
* TODOFollowing_Davids_template.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var NordicRecipientAdminApp = require('index'); // See note below*.
* var xxxSvc = new NordicRecipientAdminApp.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new NordicRecipientAdminApp.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new NordicRecipientAdminApp.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new NordicRecipientAdminApp.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The DeliveryAddress model constructor.
     * @property {module:model/DeliveryAddress}
     */
    DeliveryAddress,

    /**
     * The DeliveryOffice model constructor.
     * @property {module:model/DeliveryOffice}
     */
    DeliveryOffice,

    /**
     * The DeliveryPoint model constructor.
     * @property {module:model/DeliveryPoint}
     */
    DeliveryPoint,

    /**
     * The MailDeliveryRoute model constructor.
     * @property {module:model/MailDeliveryRoute}
     */
    MailDeliveryRoute,

    /**
     * The Metadata model constructor.
     * @property {module:model/Metadata}
     */
    Metadata,

    /**
     * The Recipient model constructor.
     * @property {module:model/Recipient}
     */
    Recipient,

    /**
     * The RecipientGroup model constructor.
     * @property {module:model/RecipientGroup}
     */
    RecipientGroup,

    /**
     * The StopPoint model constructor.
     * @property {module:model/StopPoint}
     */
    StopPoint,

    /**
     * The StopPointStopPointType model constructor.
     * @property {module:model/StopPointStopPointType}
     */
    StopPointStopPointType,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi,

    /**
    * The DeliveryAddressApi service constructor.
    * @property {module:api/DeliveryAddressApi}
    */
    DeliveryAddressApi,

    /**
    * The DeliveryPointApi service constructor.
    * @property {module:api/DeliveryPointApi}
    */
    DeliveryPointApi,

    /**
    * The RouteApi service constructor.
    * @property {module:api/RouteApi}
    */
    RouteApi
};
